// .vitepress/theme/index.ts, generated by sphinx-vitepress.
// Adapted from DocumenterVitepress.jl's theme (MIT, LuxDL contributors);
// see the third-party notices in the sphinx-vitepress LICENSE.
//
// To customize, place your own theme directory under
// <sourcedir>/.vitepress/theme/. It replaces this one entirely.
import DefaultTheme from 'vitepress/theme'
import type { Theme } from 'vitepress'
import VersionPicker from './VersionPicker.vue'

import './style.css'
import './accent.css' // generated from the `vitepress_accent` setting
import './docstrings.css'
import './overrides.css'

export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    // Referenced from nav as { component: 'VersionPicker' } on versioned builds.
    app.component('VersionPicker', VersionPicker)
  },
} satisfies Theme
