// .vitepress/theme/index.ts — generated by sphinx-vitepress.
// Adapted from DocumenterVitepress.jl's theme (MIT, LuxDL contributors);
// see NOTICE.md in the sphinx-vitepress repository.
//
// To customize, place your own theme directory under
// <sourcedir>/.vitepress/theme/ — it replaces this one entirely.
import DefaultTheme from 'vitepress/theme'

import './style.css'
import './docstrings.css'
import './overrides.css'

export default DefaultTheme
