"""User-selectable accent palettes.

The bundled theme paints links, buttons, active nav items and hero
gradients from four accent stops, supplied as CSS variables. Projects pick
a palette with ``vitepress_accent``: either a preset name (sampled from
the matplotlib colormap of the same name, so the site can match the
figures in it) or explicit colors.

Stops run dark to light and are used by role, not position, so both
themes stay readable: light mode links use ``deep`` (high contrast on
white) while dark mode uses ``bright``/``glow``.
"""

from __future__ import annotations

import re
from typing import Any

#: name -> (deep, mid, bright, glow), sampled from matplotlib colormaps.
PRESETS: dict[str, tuple[str, str, str, str]] = {
    "afmhot": ("#a93000", "#e66600", "#ff8000", "#ffb333"),
    "inferno": ("#781c6d", "#bb3754", "#ed6925", "#fbb61a"),
    "magma": ("#6b1d81", "#b63679", "#f1605d", "#fe9f6d"),
    "plasma": ("#6a00a8", "#b12a90", "#e16462", "#fca636"),
    "viridis": ("#3b528b", "#21918c", "#5ec962", "#a0da39"),
    "cividis": ("#00204d", "#31446b", "#666970", "#a69d75"),
    "ocean": ("#005b7f", "#0087b3", "#00a9c4", "#57cfd6"),
    "blue": ("#0060a8", "#0087d7", "#0c9ff4", "#5fd7ff"),
}

DEFAULT = "blue"

_HEX = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")

_ROLES = ("deep", "mid", "bright", "glow")


def _as_stops(value: Any, where: str) -> tuple[str, str, str, str]:
    if isinstance(value, str):
        if value in PRESETS:
            return PRESETS[value]
        if _HEX.match(value):
            return (value, value, value, value)
        raise ValueError(
            f"vitepress_accent{where}: {value!r} is neither a hex color nor one of "
            f"{', '.join(sorted(PRESETS))}"
        )
    if isinstance(value, (list, tuple)):
        colors = list(value)
        if len(colors) != 4 or not all(isinstance(c, str) and _HEX.match(c) for c in colors):
            raise ValueError(
                f"vitepress_accent{where}: expected 4 hex colors (deep, mid, bright, glow)"
            )
        return (colors[0], colors[1], colors[2], colors[3])
    raise TypeError(f"vitepress_accent{where}: unsupported value {value!r}")


def resolve(value: Any) -> dict[str, tuple[str, str, str, str]]:
    """Normalize ``vitepress_accent`` into ``{"light": stops, "dark": stops}``.

    Accepts a preset name, a single hex color, a 4-color sequence, or a
    mapping with ``light``/``dark`` keys holding any of those.
    """
    if not value:
        value = DEFAULT
    if isinstance(value, dict):
        light = _as_stops(value.get("light", DEFAULT), "['light']")
        dark = _as_stops(value.get("dark", value.get("light", DEFAULT)), "['dark']")
        return {"light": light, "dark": dark}
    stops = _as_stops(value, "")
    return {"light": stops, "dark": stops}


def render_css(value: Any) -> str:
    """CSS defining the accent variables the bundled theme reads."""
    palette = resolve(value)
    lines = [
        "/* Generated by sphinx-vitepress from `vitepress_accent`.",
        "   Edit that setting, not this file. */",
        ":root {",
    ]
    lines += [
        f"  --svp-accent-{role}: {color};"
        for role, color in zip(_ROLES, palette["light"], strict=True)
    ]
    lines.append("}")
    lines.append("")
    lines.append(".dark {")
    lines += [
        f"  --svp-accent-{role}: {color};"
        for role, color in zip(_ROLES, palette["dark"], strict=True)
    ]
    lines.append("}")
    lines.append("")
    return "\n".join(lines)
