"""Versioned-docs bookkeeping, ported from DocumenterVitepress.jl's model.

A deployed site is a tree of independent VitePress builds::

    gh-pages/
      stable/     # full build, base=/repo/stable/
      v1/         # full build, base=/repo/v1/
      dev/        # full build from the dev branch
      versions.js # var DOC_VERSIONS = [...]  (read by VersionPicker.vue)
      index.html  # redirect to stable/ (or dev/ if no release yet)

Each build folder carries a ``siteinfo.js`` declaring its own version; the
root ``versions.js`` is regenerated by scanning for those files, so old
versions keep working without being rebuilt.
"""

from __future__ import annotations

from pathlib import Path


def _check_segment(name: str, setting: str) -> str:
    """Reject anything that is not a single, ordinary path segment.

    Deploy folder names are joined onto the deploy directory and then
    removed, so an absolute or traversing value would delete a directory
    outside the tree.
    """
    if not name or name in (".", "..") or "/" in name or "\\" in name or Path(name).is_absolute():
        raise ValueError(f"{setting} must be a single folder name, not {name!r}")
    return name


def determine_bases(
    version: str | None, *, keep: str = "breaking", devurl: str = "dev"
) -> list[str]:
    """Deploy folder names for a build.

    ``None`` means a dev build -> ``[devurl]``. A release tag like
    ``v1.2.3`` expands according to ``keep``:

    - ``"breaking"`` (default): ``["v1", "stable"]`` (``["v0.2", "stable"]``
      for 0.x, where the minor is the breaking line)
    - ``"minor"``: ``["v1.2", "v1", "stable"]``
    - ``"patch"``: ``["v1.2.3", "v1.2", "v1", "stable"]``
    """
    if version is None:
        return [_check_segment(devurl, "devurl")]
    parts = version.removeprefix("v").split(".")
    try:
        numbers = [int(part) for part in parts]
    except ValueError as err:
        raise ValueError(f"not a release version: {version!r}") from err
    while len(numbers) < 3:
        numbers.append(0)
    major, minor, patch = numbers[:3]

    line = f"v0.{minor}" if major == 0 else f"v{major}"
    minor_base = f"v{major}.{minor}"
    patch_base = f"v{major}.{minor}.{patch}"
    if keep == "breaking":
        candidates = [line]
    elif keep == "minor":
        candidates = [minor_base, line]
    elif keep == "patch":
        candidates = [patch_base, minor_base, line]
    else:
        raise ValueError(f"keep must be 'breaking', 'minor', or 'patch', not {keep!r}")

    bases: list[str] = []
    for candidate in candidates:
        if candidate not in bases:
            bases.append(candidate)
    bases.append("stable")
    return bases


def write_siteinfo(base_dir: Path, name: str) -> None:
    """Stamp a build folder with its own version name."""
    (base_dir / "siteinfo.js").write_text(
        f'var DOCS_CURRENT_VERSION = "{name}";\n', encoding="utf-8"
    )


def _version_sort_key(name: str) -> tuple[int, ...]:
    try:
        return tuple(int(part) for part in name.removeprefix("v").split("."))
    except ValueError:
        return (-1,)


def collect_versions(deploy_dir: Path, *, devurl: str = "dev") -> list[str]:
    """Every deployed base (folders carrying a siteinfo.js), picker order:
    stable first, then dev, then releases newest-first."""
    named = [
        entry.name
        for entry in deploy_dir.iterdir()
        if entry.is_dir() and (entry / "siteinfo.js").is_file()
    ]
    ordered: list[str] = []
    if "stable" in named:
        ordered.append("stable")
    if devurl in named:
        ordered.append(devurl)
    releases = sorted(
        (name for name in named if name not in ("stable", devurl)),
        key=_version_sort_key,
        reverse=True,
    )
    ordered.extend(releases)
    return ordered


def write_versions_js(deploy_dir: Path, versions: list[str]) -> None:
    listed = ", ".join(f'"{name}"' for name in versions)
    (deploy_dir / "versions.js").write_text(f"var DOC_VERSIONS = [{listed}];\n", encoding="utf-8")


def write_root_redirect(deploy_dir: Path, target: str) -> None:
    (deploy_dir / "index.html").write_text(
        "<!DOCTYPE html>\n"
        '<html><head><meta charset="utf-8">\n'
        f'<meta http-equiv="refresh" content="0; url={target}/">\n'
        f'<link rel="canonical" href="{target}/">\n'
        f'</head><body><a href="{target}/">Redirecting to {target}/ …</a></body></html>\n',
        encoding="utf-8",
    )
