import { defineConfig } from 'vitepress'

// Generated by sphinx-vitepress.
// To customize: place your own config.mts under <sourcedir>/.vitepress/ —
// it replaces this template, and any substitution placeholders in it (see
// sphinx_vitepress/config_writer.py) are filled in at build time.
export default defineConfig({
  title: __SVP_TITLE__,
  description: __SVP_DESCRIPTION__,
  base: __SVP_BASE__,
  cleanUrls: true,
  head: __SVP_HEAD__,
  markdown: { math: true },
  vite: {
    define: {
      // Vite define values are raw replacement source text, hence the
      // double encoding via JSON.stringify.
      __DOCS_DEPLOY_ROOT__: JSON.stringify(__SVP_DEPLOY_ROOT_VALUE__),
    },
  },
  themeConfig: {
    nav: __SVP_NAV__,
    sidebar: __SVP_SIDEBAR__,
    outline: { level: [2, 3] },
    search: { provider: 'local', options: { detailedView: true } },
  },
})
